packages:
  - "."
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@google/genai': true
  '@tailwindcss/oxide': true
  bufferutil: false
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true

overrides:
  esbuild: ^0.25.11
  fast-xml-parser: ^5.5.7
  flatted: ^3.4.2
  glob: ^10.5.0
  lodash: ^4.17.23
  tar: ^7.5.11
