export * from './effects';
export * from './patches';
export * from './security';
export * from './commands';
export * from './events';
export * from './canonicalStream';
export const PROTOCOL_VERSION = '1.0.0';
import type { IpcCommand, IpcResponse } from './commands';
import type { TaskEvent } from './events';
export type CommandOfType<T extends IpcCommand['type']> = Extract<IpcCommand, { type: T }>;
export type IpcResponseOfType<T extends IpcResponse['type']> = Extract<IpcResponse, { type: T }>;
export type EventOfType<T extends TaskEvent['type']> = Extract<TaskEvent, { type: T }>;
