// sidecar/src/protocol/protocol_schema.ts
//
// Compatibility entrypoint for legacy imports.
// Prefer importing from sidecar/src/protocol/index.ts directly.

export {
    // Effects
    EffectTypeSchema,
    EffectSourceSchema,
    ConfirmationPolicySchema,
    EffectScopeSchema,
    EffectRequestSchema,
    EffectResponseSchema,
    DEFAULT_EFFECT_POLICIES,
    EFFECT_RISK_LEVELS,
    type EffectType,
    type EffectSource,
    type ConfirmationPolicy,
    type EffectScope,
    type EffectRequest,
    type EffectResponse,

    // Events
    TaskEventSchema,
    TaskStartedEventSchema,
    PlanUpdatedEventSchema,
    TaskFinishedEventSchema,
    TaskFailedEventSchema,
    ToolCalledEventSchema,
    ToolResultEventSchema,
    EffectRequestedEventSchema,
    EffectApprovedEventSchema,
    EffectDeniedEventSchema,
    PatchProposedEventSchema,
    PatchAppliedEventSchema,
    PatchRejectedEventSchema,
    AgentIdentityEstablishedEventSchema,
    AgentDelegationEventSchema,
    McpGatewayDecisionEventSchema,
    RuntimeSecurityAlertEventSchema,
    TextDeltaEventSchema,
    type TaskEvent,
    type TaskStartedEvent,
    type PlanUpdatedEvent,
    type TaskFinishedEvent,
    type TaskFailedEvent,
    type ToolCalledEvent,
    type ToolResultEvent,
    type EffectRequestedEvent,
    type EffectApprovedEvent,
    type EffectDeniedEvent,
    type PatchProposedEvent,
    type PatchAppliedEvent,
    type PatchRejectedEvent,
    type AgentIdentityEstablishedEvent,
    type AgentDelegationEvent,
    type McpGatewayDecisionEvent,
    type RuntimeSecurityAlertEvent,
    type TextDeltaEvent,

    // Patches
    PatchOperationSchema,
    DiffHunkSchema,
    FilePatchSchema,
    PatchSetSchema,
    ShadowFileSchema,
    PatchApplyRequestSchema,
    PatchApplyResultSchema,
    createDiffHeader,
    calculatePatchStats,
    type PatchOperation,
    type DiffHunk,
    type FilePatch,
    type PatchSet,
    type ShadowFile,
    type PatchApplyRequest,
    type PatchApplyResult,

    // Identity and security
    AgentIdentitySchema,
    AgentDelegationSchema,
    McpGatewayDecisionSchema,
    RuntimeSecurityAlertSchema,
    type AgentIdentity,
    type AgentDelegation,
    type McpGatewayDecision,
    type RuntimeSecurityAlert,

    // Commands
    IpcCommandSchema,
    IpcResponseSchema,
    StartTaskCommandSchema,
    CancelTaskCommandSchema,
    RequestEffectCommandSchema,
    ApplyPatchCommandSchema,
    ReadFileCommandSchema,
    ListDirCommandSchema,
    ExecShellCommandSchema,
    CaptureScreenCommandSchema,
    GetPolicyConfigCommandSchema,
    ToolpackRuntimeSchema,
    ToolpackSourceSchema,
    ToolpackManifestSchema,
    ToolpackRecordSchema,
    ListToolpacksCommandSchema,
    ListToolpacksResponseSchema,
    GetToolpackCommandSchema,
    GetToolpackResponseSchema,
    InstallToolpackCommandSchema,
    InstallToolpackResponseSchema,
    SetToolpackEnabledCommandSchema,
    SetToolpackEnabledResponseSchema,
    RemoveToolpackCommandSchema,
    RemoveToolpackResponseSchema,
    ClaudeSkillSourceSchema,
    ClaudeSkillManifestSchema,
    ClaudeSkillRecordSchema,
    ListClaudeSkillsCommandSchema,
    ListClaudeSkillsResponseSchema,
    GetClaudeSkillCommandSchema,
    GetClaudeSkillResponseSchema,
    ImportClaudeSkillCommandSchema,
    ImportClaudeSkillResponseSchema,
    SetClaudeSkillEnabledCommandSchema,
    SetClaudeSkillEnabledResponseSchema,
    RemoveClaudeSkillCommandSchema,
    RemoveClaudeSkillResponseSchema,
    RegisterAgentIdentityCommandSchema,
    RegisterAgentIdentityResponseSchema,
    RecordAgentDelegationCommandSchema,
    RecordAgentDelegationResponseSchema,
    ReportMcpGatewayDecisionCommandSchema,
    ReportMcpGatewayDecisionResponseSchema,
    ReportRuntimeSecurityAlertCommandSchema,
    ReportRuntimeSecurityAlertResponseSchema,
    ValidateGitHubUrlCommandSchema,
    ValidateGitHubUrlResponseSchema,
    ScanDefaultReposCommandSchema,
    ScanDefaultReposResponseSchema,
    type IpcCommand,
    type IpcResponse,
    type StartTaskCommand,
    type CancelTaskCommand,
    type RequestEffectCommand,
    type ApplyPatchCommand,
    type ExecShellCommand,
    type ToolpackRuntime,
    type ToolpackSource,
    type ToolpackManifest,
    type ToolpackRecord,
    type ListToolpacksCommand,
    type ListToolpacksResponse,
    type GetToolpackCommand,
    type GetToolpackResponse,
    type InstallToolpackCommand,
    type InstallToolpackResponse,
    type SetToolpackEnabledCommand,
    type SetToolpackEnabledResponse,
    type RemoveToolpackCommand,
    type RemoveToolpackResponse,
    type ClaudeSkillSource,
    type ClaudeSkillManifest,
    type ClaudeSkillRecord,
    type ListClaudeSkillsCommand,
    type ListClaudeSkillsResponse,
    type GetClaudeSkillCommand,
    type GetClaudeSkillResponse,
    type ImportClaudeSkillCommand,
    type ImportClaudeSkillResponse,
    type SetClaudeSkillEnabledCommand,
    type SetClaudeSkillEnabledResponse,
    type RemoveClaudeSkillCommand,
    type RemoveClaudeSkillResponse,
    type RegisterAgentIdentityCommand,
    type RegisterAgentIdentityResponse,
    type RecordAgentDelegationCommand,
    type RecordAgentDelegationResponse,
    type ReportMcpGatewayDecisionCommand,
    type ReportMcpGatewayDecisionResponse,
    type ReportRuntimeSecurityAlertCommand,
    type ReportRuntimeSecurityAlertResponse,
    type ValidateGitHubUrlCommand,
    type ValidateGitHubUrlResponse,
    type ScanDefaultReposCommand,
    type ScanDefaultReposResponse,
    ListWorkspacesCommandSchema,
    ListWorkspacesResponseSchema,
    CreateWorkspaceCommandSchema,
    CreateWorkspaceResponseSchema,
    DeleteWorkspaceCommandSchema,
    DeleteWorkspaceResponseSchema,
    InstallFromGitHubCommandSchema,
    InstallFromGitHubResponseSchema,
    type ListWorkspacesCommand,
    type ListWorkspacesResponse,
    type CreateWorkspaceCommand,
    type CreateWorkspaceResponse,
    type DeleteWorkspaceCommand,
    type DeleteWorkspaceResponse,
    type InstallFromGitHubCommand,
    type InstallFromGitHubResponse,
} from './index';
